var TEXT="",LANG="",TRANSLATIONS="",TERM="",DELIM="",WIDTH=parseInt($("body").width()/3);178<WIDTH&&(WIDTH=178);100>WIDTH&&(WIDTH=100);var HEIGHT=parseInt(118*WIDTH/178),ARROW_SIZE=parseInt(WIDTH/3.28);
$(document).ready(function(){$("body").prepend("<style>\n#gallery>li{width: "+WIDTH+"px;}\n.widget{width: "+3*WIDTH+"px;}\n.shadow{height: "+HEIGHT+"px;}\ndiv.prev .prev, div.next .next {top: "+ARROW_SIZE+"px;font-size: "+ARROW_SIZE+"px;}\n</style>");var a=window.parent.frames.ro;"undefined"==typeof a&&(a=window.opener);$("#img_sel").on("change",function(){location.href="ggl_img.php?q="+$(this).val()});$("#gallery").width(6*WIDTH);$(".arrowoverlay").height(HEIGHT);getGoogleThumbnails(TEXT,LANG,0,
6);var b=$('[name="WoTranslation"]',a.document).val();if("undefined"!=typeof a)if(b.length){var c=$('[name="WoText"]',a.document).val();$("#img_sel").append('<option class="red">'+c+"</option>");""!=b&&"*"!=b&&jQuery.each(b.split(DELIM),function(a,b){var d=b.trim();if(d!=c){var e="";d==TEXT&&(e=' selected="selected"');$("#img_sel").append("<option"+e+">"+d+"</option>")}})}else $("#new_search").text("(add translation and reload for more search options)");else $("#new_search").text(""),$("#del_image").remove()});
$(window).load(function(){$(document).on("click",".shadow",click_thumbnail).on("click",".arrowoverlay.prev",{width:WIDTH},click_prev_thumbnails).on("click",".arrowoverlay.next",{width:WIDTH},click_next_thumbnails)});
function getThumbnailsFromApi(a){try{$.each(a.responseData.results,function(a,b){$("#gallery").append('<li><div><div class="shadow" style="background-image: url(\''+b.tbUrl+"');\"></div></div></li>")})}catch(b){$("#gallery").addClass("endLoad"),$(".next").css("z-index",0).prop("disabled",!0)}}
function getGoogleThumbnails(a,b,c,f){""!=b&&(b="&hl="+b);$.ajax({url:"https://ajax.googleapis.com/ajax/services/search/images?v=1.0&q="+a+b+"&rsz="+f+"&start="+c+"&callback=?",type:"GET",dataType:"jsonp",jsonp:"getThumbnailsFromApi",jsonpCallback:"getThumbnailsFromApi",async:"true"})}
function click_next_thumbnails(a){var b=parseInt($("#gallery").css("left"));0==b%a.data.width&&(0==b&&$(".prev").css("z-index",6).prop("disabled",!1),$(".next>.next").css({color:"#F00"}).animate({color:"#EEE"},250,function(){}),7>$("#gallery>li .shadow").length+b/a.data.width&&(4>$("#gallery>li .shadow").length+b/a.data.width?$(".next").css("z-index",0).prop("disabled",!0):(getGoogleThumbnails(TEXT,LANG,$("li .shadow").length+1,6),a=$("#gallery").width()+6*a.data.width,$("#gallery").width(a))),$("#gallery>li .shadow:visible:last").offset().left>
3.2*WIDTH||!$("#gallery.endLoad").length?$("#gallery").animate({left:b-3*WIDTH},200,function(){}):$(".next").css("z-index",0).prop("disabled",!0))}function click_prev_thumbnails(a){var b=parseInt($("#gallery").css("left"));0==b%a.data.width&&0>b&&(b==-3*a.data.width&&$(".prev").css("z-index",0),$(".prev>.prev").css({color:"#F00"}).animate({color:"#EEE"},250,function(){}),$("#gallery").animate({left:b+3*a.data.width},200,function(){}),$(".next").css("z-index",6).prop("disabled",!1))}
function click_thumbnail(a){$(".shadowred").removeClass("shadowred");var b=window.parent.frames.ro;"undefined"==typeof b&&(b=window.opener);"undefined"==typeof b?alert("Image can not be copied!"):($(a.target).addClass("shadowred"),$("#thumbnail",b.document).css("background-image",$(a.target).css("background-image")),$('[name="WoImage"]',b.document).val($(a.target).css("background-image").replace("url(","").replace(")","")).trigger("change"),b.makeDirty())}
function deleteImage(){var a=window.parent.frames.ro;"undefined"==typeof a&&(a=window.opener);$('[name="WoImage"]',a.document).val("DEL");$("#thumbnail",a.document).removeAttr("style");$(".shadowred").removeClass("shadowred");a.makeDirty()};
