(function(a){a.fn.get_adv_xpath=function(){a("#adv").prepend("<p style=\"text-align: left;\"><input style=\"vertical-align: middle; margin: 2px;\" class=\"xpath\" type=\"radio\" name=\"xpath\" value=''>custom: <input type=\"text\" id=\"custom_xpath\" name=\"custom_xpath\" style=\"width:70%\" onkeyup=\"try{val=$('#custom_xpath').val();valid=$(document).xpath(val);}catch(err){val='';valid=0;}if(valid==0){$(this).parent().find('.xpath').val('');if($(this).parent().find(':radio').is(':checked'))$('#adv_get_button').prop('disabled', true);$('#custom_img').attr('src','icn/exclamation-red.png');}else {$(this).parent().find('.xpath').val(val);if($(this).parent().find(':radio').is(':checked'))$('#adv_get_button').prop('disabled', false);$('#custom_img').attr('src','icn/tick.png');}return false;\" onpaste=\"setTimeout(function() {try{val=$('#custom_xpath').val();valid=$(document).xpath(val);}catch(err){val='';valid=0;}if(valid==0){$(this).parent().find('.xpath').val('');if($('#custom_xpath').parent().find(':radio').is(':checked'))$('#adv_get_button').prop('disabled', true);$('#custom_img').attr('src','icn/exclamation-red.png');}else {$('#custom_xpath').parent().find('.xpath').val(val);if($('#custom_xpath').parent().find(':radio').is(':checked'))$('#adv_get_button').prop('disabled', false);$('#custom_img').attr('src','icn/tick.png');}}, 0);\" value=''></input><img id=\"custom_img\" src=\"icn/exclamation-red.png\" alt=\"-\" /></input></p>");
a("#adv").show();a("*").removeClass("lwt_marked_text");a("*[class='']").removeAttr("class");for(var h=a(a("#mark_action :selected").data()).get(0).tagName.toLowerCase(),n=0,d="",k="",l="",b=0,c=this[0].attributes,q=c.length;b<q;b++){if("id"==c.item(b).nodeName)for(var g=c.item(b).nodeValue.split(" "),e=0;e<g.length;e++){var m='//*[@id[contains(concat(" ",normalize-space(.)," ")," '+g[e]+' ")]]';a("#adv").prepend('<p style="text-align: left;"><input style="vertical-align: middle; margin: 2px;" class="xpath" type="radio" name="xpath" value=\''+
m+"'>contains id: \u00ab"+g[e]+"\u00bb</input></p>")}if("class"==c.item(b).nodeName)for(var f=c.item(b).nodeValue.split(" "),e=0;e<f.length;e++)m='//*[@class[contains(concat(" ",normalize-space(.)," ")," '+f[e]+' ")]]',a("#adv").prepend('<p style="text-align: left;"><input style="vertical-align: middle; margin: 2px;" class="xpath" type="radio" name="xpath" value=\''+m+"'>contains class: \u00ab"+f[e]+"\u00bb</input></p>");0<b&&(d+=" and ");0==b&&(d+="[");d+="@"+c.item(b).nodeName;d+='="'+c.item(b).nodeValue+
'"';b==c.length-1&&(d+="]")}this.parents().each(function(){for(var p=a(this).get(0),c=0,e=p.attributes,d=e.length;c<d;c++){if(0==n){if("id"==e.item(c).nodeName){g=e.item(c).nodeValue.split(" ");for(var b=0;b<g.length;b++)m='//*[@id[contains(concat(" ",normalize-space(.)," ")," '+g[b]+' ")]]',a("#adv").prepend('<p style="text-align: left;"><input style="vertical-align: middle; margin: 2px;" class="xpath" type="radio" name="xpath" value=\''+m+"/"+h+"'>parent contains id: \u00ab"+g[b]+"\u00bb</input></p>")}if("class"==
e.item(c).nodeName)for(f=e.item(c).nodeValue.split(" "),b=0;b<f.length;b++)"lwt_filtered_text"!=f[b]&&(m='//*[@class[contains(concat(" ",normalize-space(.)," ")," '+f[b]+' ")]]',a("#adv").prepend('<p style="text-align: left;"><input style="vertical-align: middle; margin: 2px;" class="xpath" type="radio" name="xpath" value=\''+m+"/"+h+"'>parent contains class: \u00ab"+f[b]+"\u00bb</input></p>"))}if(1<e.length||"lwt_filtered_text"!=e.item(c).nodeValue)0<c&&"lwt_filtered_text"!=e.item(c).nodeValue&&
(k+=" and "),0==c&&(k+="["),"lwt_filtered_text"!=e.item(c).nodeValue&&(k+="@"+e.item(c).nodeName),"lwt_filtered_text"!=e.item(c).nodeValue&&(k+='="'+e.item(c).nodeValue.replace("lwt_filtered_text","").trim()+'"'),c==e.length-1&&(k+="]")}l=p.tagName.toLowerCase()+k+"/"+l;k="";n++});a("#adv").prepend('<p style="text-align: left;"><input style="vertical-align: middle; margin: 2px;" class="xpath" type="radio" name="xpath" value=\'/'+l+h+d+"'>all: \u00ab /"+l.replace('=""',"")+h+d.replace('=""',"")+" \u00bb</input></p>");
a('#adv input[type="radio"]').each(function(c){"undefined"==typeof c&&(c=1);"undefined"==typeof a(this).attr("id")&&a(this).attr("id","rb_"+c++);a(this).after('<label class="wrap_radio" for="'+a(this).attr("id")+'"><span></span></label>')})}})(jQuery);
$(function(){""==$("#lwt_sel").html()&&2==$("input[name='step']").val()?$("#next").prop("disabled",!0):$("#next").prop("disabled",!1);$("#lwt_last").css("margin-top",$("#lwt_header").height());$("#lwt_header").nextAll().click(function(a){if($(a.target).hasClass("lwt_selected_text")){var d=[],k=[];$(".lwt_selected_text").each(function(){d.push(this)});$(a.target).parents("*").addBack().each(function(){if(!$(this).parent().hasClass("lwt_selected_text")&&$(this).hasClass("lwt_selected_text"))if($(this).hasClass("lwt_highlighted_text"))$("*").removeClass("lwt_highlighted_text");
else{el=this;$("*").removeClass("lwt_selected_text");k=[];$(this).parents(".lwt_filtered_text").each(function(){$(this).removeClass("lwt_filtered_text");k.push(this)});$("*[class='']").removeAttr("class");$("#lwt_sel li").each(function(){$("*").removeClass("lwt_highlighted_text");$(this).addClass("lwt_highlighted_text");$(document).xpath($(this).text()).addClass("lwt_highlighted_text");if($(el).hasClass("lwt_highlighted_text"))return!1});for(var a in d)$(d[a]).addClass("lwt_selected_text")}});for(b in k)$(k[b]).addClass("lwt_filtered_text");
$('button[name="button"]').prop("disabled",!0);$("#mark_action").empty();$("<option/>").val("").text("[Click On Text]").appendTo("#mark_action");return!1}if($(a.target).hasClass("lwt_filtered_text"))a.preventDefault();else{if($(a.target).hasClass("lwt_marked_text"))$("#mark_action").empty(),$("*").removeClass("lwt_marked_text"),$("*[class='']").removeAttr("class"),$('button[name="button"]').prop("disabled",!0),$("<option/>").val("").text("[Click On Text]").appendTo("#mark_action");else{$("*").removeClass("lwt_marked_text");
$("#mark_action").empty();var k=[];$(a.target).parents(":not(html,body)").addBack().each(function(){if(!$(this).hasClass("lwt_filtered_text")){k=[];$(this).parents(".lwt_filtered_text").each(function(){$(this).removeClass("lwt_filtered_text");k.push(this)});$("*[class='']").removeAttr("class");""===$(this).attr("style")&&$(this).removeAttr("style");val1=$(this).get(0).tagName.toLowerCase();for(var c="",b="",g="",e="",h="",e="0"!=$('select[name="select_mode"]').val()?5:$(this).attr("id")?1:$(this).parent().attr("id")?
2:$(this).attr("class")?3:$(this).parent().attr("class")?4:5,f=0,d=this.attributes,l=d.length;f<l;f++)if(5==e||"class"==d.item(f).nodeName&&1!=e||"id"==d.item(f).nodeName)c+=d.item(f).nodeName,c+='="'+d.item(f).nodeValue+'" ',0<f&&(b+=" and "),b+="@"+d.item(f).nodeName,b+='="'+d.item(f).nodeValue+'"';c=c.replace('=""',"").trim();b&&(b="["+b+"]");if(1!=e&&3!=e){f=0;d=$(this).parent().get(0).attributes;for(l=d.length;f<l;f++)if(5==e||"class"==d.item(f).nodeName&&2!=e||"id"==d.item(f).nodeName)0<f&&
(g+=" and "),g+="@"+d.item(f).nodeName,g+='="'+d.item(f).nodeValue+'"';g&&(g="["+g+"]");h=$(this).parent().get(0).tagName.toLowerCase()+g+"\u00a7"}h=h.replace("body\u00a7","");g=c.substr(0,20);g!=c&&(g+="... ");""!=g&&(g=" "+g);a.target==this?$("<option/>").val("//"+h.replace('=""',"").replace("[ and @","[@")+val1+b.replace('=""',"").replace("[ and @","[@")).text("<"+val1.replace("[ and @","[@")+g.replace("[ and @","[@")+">").data(this).attr("selected",!0).prependTo("#mark_action"):$("<option/>").val("//"+
h.replace('=""',"").replace("[ and @","[@")+val1+b.replace('=""',"").replace("[ and @","[@")).text("<"+val1.replace("[ and @","[@")+g.replace("[ and @","[@")+">").data(this).prependTo("#mark_action");for(f in k)$(k[f]).addClass("lwt_filtered_text")}});$('button[name="button"]').prop("disabled",!1);var h=$("#mark_action").val(),h=h.replace(/@/g,"").replace("//","").replace(/ and /g,"][").replace("\u00a7",">"),k=[];$(this).parents(".lwt_filtered_text").each(function(){$(this).removeClass("lwt_filtered_text");
k.push(this)});$(h+":not(.lwt_selected_text)").find("*:not(.lwt_selected_text)").addBack().addClass("lwt_marked_text");for(var b in k)$(k[b]).addClass("lwt_filtered_text")}return!1}});$("*").removeClass("lwt_filtered_text");$("*[class='']").removeAttr("class");var a="";$("#lwt_sel li").each(function(){$(this).hasClass("lwt_highlighted_text")?$(document).xpath($(this).text()).not($("#lwt_header").find("*").addBack()).addClass("lwt_highlighted_text").find("*").addBack().addClass("lwt_selected_text"):
a+=$(this).text()+" | "});""!=a&&$(document).xpath(a.replace(/ \| $/,"")).find("*").addBack().not($("#lwt_header").find("*").addBack()).addClass("lwt_selected_text");for(var h in filter_Array)$(filter_Array[h]).addClass("lwt_filtered_text");$("*[style='']").removeAttr("style");$("#lwt_header select").wrap("<label class='wrap_select'></label>");$(document).mouseup(function(){$("select:not(:active),button,input[type=button],.wrap_radio span,.wrap_checkbox span").blur()})});
$(document).on("click",".delete_selection",function(){$("*").removeClass("lwt_selected_text").removeClass("lwt_marked_text");$("*").removeClass("lwt_filtered_text");$("#lwt_header").nextAll().find("*").addBack().removeClass("lwt_highlighted_text");$(this).parent().remove();var a="";$("#lwt_sel li").each(function(){$(this).hasClass("lwt_highlighted_text")?$(document).xpath($(this).text()).not($("#lwt_header").find("*").addBack()).addClass("lwt_highlighted_text").find("*").addBack().addClass("lwt_selected_text"):
a+=$(this).text()+" | "});""!=a&&$(document).xpath(a.replace(/ \| $/,"")).find("*").addBack().not($("#lwt_header").find("*").addBack()).addClass("lwt_selected_text");for(var h in filter_Array)$(filter_Array[h]).addClass("lwt_filtered_text");$("*[class='']").removeAttr("class");$("*[style='']").removeAttr("style");$("#lwt_last").css("margin-top",$("#lwt_header").height());""==$("#lwt_sel").html()&&2==$("input[name='step']").val()&&$("#next").prop("disabled",!0);return!1});
$(document).on("change",".xpath",function(){$("#adv_get_button").prop("disabled",!1);$(this).parent().find("img").each(function(){"icn/exclamation-red.png"==$(this).attr("src")&&$("#adv_get_button").prop("disabled",!0)});return!1});
$(document).on("click","#adv_get_button",function(){$("*").removeClass("lwt_filtered_text");$("*[class='']").removeAttr("class");"undefined"!=typeof $("#adv :radio:checked").val()&&($("#lwt_sel").append("<li style='text-align: left'><img class='delete_selection' src='icn/cross.png'  title='Delete Selection' alt='' /> "+$("#adv :radio:checked").val()+"</li>"),$(document).xpath($("#adv :radio:checked").val()).find("*").addBack().not($("#lwt_header").find("*").addBack()).addClass("lwt_selected_text"),
$("#next").prop("disabled",!1));$("#adv").hide();$("#lwt_last").css("margin-top",$("#lwt_header").height());for(var a in filter_Array)$(filter_Array[a]).addClass("lwt_filtered_text");return!1});
$(document).on("click","#lwt_sel li",function(){if($(this).hasClass("lwt_highlighted_text"))$("*").removeClass("lwt_highlighted_text");else{var a=[];$(".lwt_selected_text").each(function(){$(this).removeClass("lwt_selected_text");a.push(this)});$("*").removeClass("lwt_filtered_text");$("*").removeClass("lwt_highlighted_text");$("*[class='']").removeAttr("class");$(this).addClass("lwt_highlighted_text");$(document).xpath($(this).text()).not($("#lwt_header").find("*").addBack()).addClass("lwt_highlighted_text").find("*").addBack().addClass("lwt_selected_text");
for(var h in filter_Array)$(filter_Array[h]).addClass("lwt_filtered_text");for(h in a)$(a[h]).addClass("lwt_selected_text")}return!1});
$(document).on("change","#mark_action",function(){$("*").removeClass("lwt_marked_text");$("*[class='']").removeAttr("class");attr=$("#mark_action").val();attr=attr.replace(/@/g,"").replace("//","").replace(/ and /g,"][").replace("\u00a7",">");$("*").removeClass("lwt_filtered_text");$(attr).find("*:not(.lwt_selected_text)").addBack().addClass("lwt_marked_text");for(var a in filter_Array)$(filter_Array[a]).addClass("lwt_filtered_text");return!1});
$(document).on("click","#get_button,#filter_button",function(){$("*").removeClass("lwt_marked_text");if("adv"==$("select[name='select_mode']").val())$("#adv p").remove(),$("*[style='']").removeAttr("style"),$("#adv_get_button").prop("disabled",!0),$($("#mark_action :selected").data()).get_adv_xpath();else{$("#next").prop("disabled",!1);attr=$("#mark_action").val();attr=attr.replace(/@/g,"").replace("//","").replace(/ and /g,"][").replace("\u00a7",">");var a=[];$(".lwt_filtered_text").each(function(){$(this).removeClass("lwt_filtered_text");
a.push(this)});$("*").removeClass("lwt_filtered_text");$(attr).find("*").addBack().addClass("lwt_selected_text");for(var h in a)$(a[h]).addClass("lwt_filtered_text");$("#lwt_sel").append("<li style='text-align: left'><img class='delete_selection' src='icn/cross.png'  title='Delete Selection' alt='"+$("#mark_action").val()+"' /> "+$("#mark_action").val().replace("\u00a7","/")+"</li>")}$(this).prop("disabled",!0);$("#mark_action").empty();$("<option/>").val("").text("[Click On Text]").appendTo("#mark_action");
$("#lwt_last").css("margin-top",$("#lwt_header").height());return!1});
$(document).on("click","#next",function(){$("#article_tags,#filter_tags").val($("#lwt_sel").html()).prop("disabled",!1);var a=$("#lwt_sel li").map(function(){return $(this).text()}).get().join(" | ");$("input[name='html']").val(a);a=$("input[name='step']").val();2==a&&($("input[name='html']").attr("name","article_selector"),$("select[name='NfArticleSection'] option").each(function(){art_sec=$("#lwt_sel li").map(function(){return $(this).text()}).get().join(" | ");$(this).val(art_sec)}));$("input[name='step']").val(++a);
document.lwt_form1.submit();return!1});$(document).on("change","#host_status",function(){var a=$(this).val(),h=$("input[name='host_name']").val();$("select[name='selected_feed'] option").each(function(){var n=$(this).text();n.replace(/[\u25b8\-][0-9\s]*[\u2605\u2606\-][\s]*host:/,"").trim()==h.trim()&&$(this).text(n.replace(/([\u25b8\-][0-9\s]*?)\s[\u2605\u2606\-]\s(.*)/,"$1 "+a.trim()+" $2"))});return!1});
