/**
 * \file
 * \brief LWT Javascript functions
 * 
 * @package Lwt
 * @author  andreask7 <andreasks7@users.noreply.github.com>
 * @license Unlicense <http://unlicense.org/>
 * @since   1.6.16-fork
 */
var ol_textfont='"Lucida Grande",Arial,sans-serif,STHeiti,"Arial Unicode MS",MingLiu';var ol_textsize=3;var ol_sticky=1;var ol_captionfont='"Lucida Grande",Arial,sans-serif,STHeiti,"Arial Unicode MS",MingLiu';var ol_captionsize=3;var ol_width=260;var ol_close='Close';var ol_offsety=30;var ol_offsetx=3;var ol_fgcolor='#FFFFE8';var ol_closecolor='#FFFFFF';function run_overlib_status_98(wblink1,wblink2,wblink3,hints,txid,torder,txt,wid,multi_words,rtl,ann){return overlib('<b>'+escape_html_chars_2(hints,ann)+'</b><br /> '+make_overlib_link_new_word(txid,torder,wid)+' | '+make_overlib_link_delete_word(txid,wid)+make_overlib_link_new_multiword(txid,torder,multi_words,rtl)+' <br /> '+make_overlib_link_wb(wblink1,wblink2,wblink3,txt,txid,torder),CAPTION,'Word')}
function run_overlib_status_99(wblink1,wblink2,wblink3,hints,txid,torder,txt,wid,multi_words,rtl,ann){return overlib('<b>'+escape_html_chars_2(hints,ann)+'</b><br /> '+make_overlib_link_new_word(txid,torder,wid)+' | '+make_overlib_link_delete_word(txid,wid)+make_overlib_link_new_multiword(txid,torder,multi_words,rtl)+' <br /> '+make_overlib_link_wb(wblink1,wblink2,wblink3,txt,txid,torder),CAPTION,'Word')}
function run_overlib_status_1_to_5(wblink1,wblink2,wblink3,hints,txid,torder,txt,wid,stat,multi_words,rtl,ann){return overlib('<b>'+escape_html_chars_2(hints,ann)+'</b><br /> '+make_overlib_link_change_status_all(txid,torder,wid,stat)+' <br /> '+make_overlib_link_edit_word(txid,torder,wid)+' | '+make_overlib_link_delete_word(txid,wid)+make_overlib_link_new_multiword(txid,torder,multi_words,rtl)+' <br /> '+make_overlib_link_wb(wblink1,wblink2,wblink3,txt,txid,torder),CAPTION,make_overlib_link_edit_word_title('Word &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;',txid,torder,wid))}
function run_overlib_status_unknown(wblink1,wblink2,wblink3,hints,txid,torder,txt,multi_words,rtl){return overlib('<b>'+escape_html_chars(hints)+'</b><br /> '+make_overlib_link_wellknown_word(txid,torder)+' <br /> '+make_overlib_link_ignore_word(txid,torder)+make_overlib_link_new_multiword(txid,torder,multi_words,rtl)+' <br /> '+make_overlib_link_wb(wblink1,wblink2,wblink3,txt,txid,torder),CAPTION,'New Word')}
function run_overlib_multiword(wblink1,wblink2,wblink3,hints,txid,torder,txt,wid,stat,wcnt,ann){return overlib('<b>'+escape_html_chars_2(hints,ann)+'</b><br /> '+make_overlib_link_change_status_all(txid,torder,wid,stat)+' <br /> '+make_overlib_link_edit_multiword(txid,torder,wid)+' | '+make_overlib_link_delete_multiword(txid,wid)+' <br /> '+make_overlib_link_wb(wblink1,wblink2,wblink3,txt,txid,torder),CAPTION,make_overlib_link_edit_multiword_title(wcnt.trim()+'-Word-Expression',txid,torder,wid))}
function run_overlib_test(wblink1,wblink2,wblink3,wid,txt,trans,roman,stat,sent,todo,oldstat){const s=parseInt(stat,10);let c=s+1;if(c>5)c=5;let w=s-1;if(w<1)w=1;let cc=stat+' ▶ '+c;if(c==s)cc=c;let ww=stat+' ▶ '+w;if(w==s)ww=w;let overlib_string='';if(todo==1){overlib_string+='<center><hr noshade size=1 /><b>';if(stat>=1&&stat<=5){overlib_string+=make_overlib_link_change_status_test(wid,1,'<img src="icn/thumb-up.png" title="Got it!" alt="Got it!" /> Got it! ['+cc+']')+'<hr noshade size=1 />'+make_overlib_link_change_status_test(wid,-1,'<img src="icn/thumb.png" title="Oops!" alt="Oops!" /> Oops! ['+ww+']')+'<hr noshade size=1 />'}
overlib_string+=make_overlib_link_change_status_alltest(wid,stat)+'</b></center><hr noshade size=1 />'}
overlib_string+='<b>'+escape_html_chars(make_tooltip(txt,trans,roman,stat))+'</b><br />'+' <a href="edit_tword.php?wid='+wid+'" target="ro" onclick="showRightFrames();">Edit term</a><br />'+createTheDictLink(wblink1,txt,'Dict1','Lookup Term: ')+createTheDictLink(wblink2,txt,'Dict2','')+createTheDictLink(wblink3,txt,'GTr','')+createTheDictLink(wblink3,sent,'GTr','<br />Lookup Sentence:');return overlib(overlib_string,CAPTION,'Got it?')}
function make_overlib_link_new_multiword(txid,torder,multi_words,rtl){if(multi_words.every((x)=>!x))return'';let output=' <br />Expr: ';if(rtl){for(var i=7;i<0;i--){output+=(multi_words[i]?make_overlib_link_create_edit_multiword_rtl(i+2,txid,torder,multi_words[i])+' ':'')}}else{for(var i=0;i<7;i++){output+=(multi_words[i]?make_overlib_link_create_edit_multiword_rtl(i+2,txid,torder,multi_words[i])+' ':'')}}
output+=' ';return output}
function make_overlib_link_wb(wblink1,wblink2,wblink3,txt,txid,torder){const s=createTheDictLink(wblink1,txt,'Dict1','Lookup Term: ')+createTheDictLink(wblink2,txt,'Dict2','')+createTheDictLink(wblink3,txt,'GTr','')+((torder<1||txid<1)?'':'<br />Lookup Sentence: '+createSentLookupLink(torder,txid,wblink3,'GTr'));return s}
function make_overlib_link_wbnl(wblink1,wblink2,wblink3,txt,txid,torder){const s=createTheDictLink(wblink1,txt,'Dict1','Term: ')+createTheDictLink(wblink2,txt,'Dict2','')+createTheDictLink(wblink3,txt,'GTr','')+((torder<1||txid<1)?'':' | Sentence: '+createSentLookupLink(torder,txid,wblink3,'GTr'));return s}
function make_overlib_link_wbnl2(wblink1,wblink2,wblink3,txt,sent){return createTheDictLink(wblink1,txt,'Dict1','Term: ')+createTheDictLink(wblink2,txt,'Dict2','')+createTheDictLink(wblink3,txt,'GTr','')+((sent=='')?'':createTheDictLink(wblink3,sent,'GTr',' | Sentence:'))}
function make_overlib_link_change_status_all(txid,torder,wid,oldstat){let result='St: ';for(let newstat=1;newstat<=5;newstat++){result+=make_overlib_link_change_status(txid,torder,wid,oldstat,newstat)}
result+=make_overlib_link_change_status(txid,torder,wid,oldstat,99);result+=make_overlib_link_change_status(txid,torder,wid,oldstat,98);return result}
function make_overlib_link_change_status_alltest(wid,oldstat){let result='';for(let newstat=1;newstat<=5;newstat++){result+=make_overlib_link_change_status_test2(wid,oldstat,newstat)}
result+=make_overlib_link_change_status_test2(wid,oldstat,99);result+=make_overlib_link_change_status_test2(wid,oldstat,98);return result}
function make_overlib_link_change_status(txid,torder,wid,oldstat,newstat){if(oldstat==newstat){return'<span title="'+getStatusName(oldstat)+'">◆</span>'}
return' <a href="set_word_status.php?tid='+txid+'&amp;ord='+torder+'&amp;wid='+wid+'&amp;status='+newstat+'" target="ro" onclick="showRightFrames();"><span title="'+getStatusName(newstat)+'">['+getStatusAbbr(newstat)+']</span></a> '}
function make_overlib_link_change_status_test2(wid,oldstat,newstat){let output=' <a href="set_test_status.php?wid='+wid+'&amp;status='+newstat+'" target="ro" onclick="showRightFrames();">'+'<span title="'+getStatusName(newstat)+'">[';output+=(oldstat==newstat)?'◆':getStatusAbbr(newstat);output+=']</span></a> ';return output}
function make_overlib_link_change_status_test(wid,plusminus,text){return' <a href="set_test_status.php?wid='+wid+'&amp;stchange='+plusminus+'" target="ro" onclick="showRightFrames();'+(plusminus>0?'successSound()':'failureSound()')+';">'+text+'</a> '}
function make_overlib_link_new_word(txid,torder,wid){return' <a href="edit_word.php?tid='+txid+'&amp;ord='+torder+'&amp;wid='+wid+'" target="ro" onclick="showRightFrames();">Learn term</a> '}
function make_overlib_link_edit_multiword(txid,torder,wid){return' <a href="edit_mword.php?tid='+txid+'&amp;ord='+torder+'&amp;wid='+wid+'" target="ro" onclick="showRightFrames();">Edit term</a> '}
function make_overlib_link_edit_multiword_title(text,txid,torder,wid){return'<a style="color:yellow" href="edit_mword.php?tid='+txid+'&amp;ord='+torder+'&amp;wid='+wid+'" target="ro" onclick="showRightFrames();">'+text+'</a>'}
function make_overlib_link_create_edit_multiword(len,txid,torder,txt){return' <a href="edit_mword.php?tid='+txid+'&amp;ord='+torder+'&amp;txt='+txt+'" target="ro" onclick="showRightFrames();">'+len+'..'+escape_html_chars(txt.substr(-2).trim())+'</a> '}
function make_overlib_link_create_edit_multiword_rtl(len,txid,torder,txt){return' <a dir="rtl" href="edit_mword.php?tid='+txid+'&amp;ord='+torder+'&amp;txt='+txt+'" target="ro" onclick="showRightFrames();">'+len+'..'+escape_html_chars(txt.substr(-2).trim())+'</a> '}
function make_overlib_link_edit_word(txid,torder,wid){const url='edit_word.php?tid='+txid+'&amp;ord='+torder+'&amp;wid='+wid;return' <a href="'+url+' " target="ro" onclick="showRightFrames()">Edit term</a> '}
function make_overlib_link_edit_word_title(text,txid,torder,wid){return'<a style="color:yellow" href="edit_word.php?tid='+txid+'&amp;ord='+torder+'&amp;wid='+wid+'" target="ro" onclick="showRightFrames();">'+text+'</a>'}
function make_overlib_link_delete_word(txid,wid){return' <a onclick="showRightFrames(); return confirmDelete();" href="delete_word.php?wid='+wid+'&amp;tid='+txid+'" target="ro">Delete term</a> '}
function make_overlib_link_delete_multiword(txid,wid){return' <a onclick="showRightFrames(); return confirmDelete();" href="delete_mword.php?wid='+wid+'&amp;tid='+txid+'" target="ro">Delete term</a> '}
function make_overlib_link_wellknown_word(txid,torder){return' <a href="insert_word_wellknown.php?tid='+txid+'&amp;ord='+torder+'" target="ro" onclick="showRightFrames();">I know this term well</a> '}
function make_overlib_link_ignore_word(txid,torder){return' <a href="insert_word_ignore.php?tid='+txid+'&amp;ord='+torder+'" target="ro" onclick="showRightFrames();">Ignore this term</a> '}
function getStatusName(status){return(STATUSES[status]?STATUSES[status].name:'Unknown')}
function getStatusAbbr(status){return(STATUSES[status]?STATUSES[status].abbr:'?')}
function translateSentence(url,sentctl){if((typeof sentctl!=='undefined')&&(url!='')){text=sentctl.value;if(typeof text==='string'){showRightFrames(undefined,createTheDictUrl(url,text.replace(/[{}]/g,'')))}}}
function translateSentence2(url,sentctl){if((typeof sentctl!=='undefined')&&(url!='')){text=sentctl.value;if(typeof text==='string'){owin(createTheDictUrl(url,text.replace(/[{}]/g,'')))}}}
function translateWord(url,wordctl){if((typeof wordctl!=='undefined')&&(url!='')){text=wordctl.value;if(typeof text==='string'){showRightFrames(undefined,createTheDictUrl(url,text))}}}
function translateWord2(url,wordctl){if((typeof wordctl!=='undefined')&&(url!='')){text=wordctl.value;if(typeof text==='string'){owin(createTheDictUrl(url,text))}}}
function translateWord3(url,word){owin(createTheDictUrl(url,word))}
function make_tooltip(word,trans,roman,status){const nl='\x0d';let title=word;if(roman!=''){if(title!='')title+=nl;title+='▶ '+roman}
if(trans!=''&&trans!='*'){if(title!='')title+=nl;title+='▶ '+trans}
if(title!='')title+=nl;title+='▶ '+getStatusName(status)+' ['+getStatusAbbr(status)+']';return title}
function escape_html_chars_2(title,ann){if(ann!=''){const ann2=escape_html_chars(ann);return escape_html_chars(title).replace(ann2,'<span style="color:red">'+ann2+'</span>')}else{return escape_html_chars(title)}}
function owin(url){window.open(url,'dictwin','width=800, height=400, scrollbars=yes, menubar=no, resizable=yes, status=no')}
function oewin(url){window.open(url,'editwin','width=800, height=600, scrollbars=yes, menubar=no, resizable=yes, status=no')}
function createTheDictUrl(u,w){const url=u.trim();const trm=w.trim();const r='trans.php?x=2&i='+escape(u)+'&t='+w;return r}
function createTheDictLink(u,w,t,b){const url=u.trim();const trm=w.trim();const txt=t.trim();const txtbefore=b.trim();let r='';if(url!=''&&txt!=''){if(url.substr(0,1)=='*'){r=' '+txtbefore+' <span class="click" onclick="owin(\''+createTheDictUrl(url.substring(1),escape_apostrophes(trm))+'\');">'+txt+'</span> '}else{r=' '+txtbefore+' <a href="'+createTheDictUrl(url,trm)+'" target="ru" onclick="showRightFrames();">'+txt+'</a> '}}
return r}
function createSentLookupLink(torder,txid,url,txt){var url=url.trim();var txt=txt.trim();let r='';if(url!=''&&txt!=''){if((url.substr(0,8)=='*http://')||(url.substr(0,9)=='*https://')){r=' <span class="click" onclick="owin(\'trans.php?x=1&i='+torder+'&t='+txid+'\');">'+txt+'</span> '}else if((url.substr(0,7)=='http://')||(url.substr(0,8)=='https://')){r=' <a href="trans.php?x=1&i='+torder+'&t='+txid+'" target="ru" onclick="showRightFrames();">'+txt+'</a> '}}
return r}
function escape_html_chars(s){return s.replace(/&/g,'%AMP%').replace(/</g,'&#060;').replace(/>/g,'&#062;').replace(/"/g,'&#034;').replace(/'/g,'&#039;').replace(/%AMP%/g,'&#038;').replace(/\x0d/g,'<br />')}
function escape_apostrophes(s){return s.replace(/'/g,'\\\'')}
function selectToggle(toggle,form){const myForm=document.forms[form];for(let i=0;i<myForm.length;i++){if(toggle){myForm.elements[i].checked='checked'}else{myForm.elements[i].checked=''}}
markClick()}
function multiActionGo(f,sel){if(f!==undefined&&sel!==undefined){const v=sel.value;const t=sel.options[sel.selectedIndex].text;if(typeof v==='string'){if(v=='addtag'||v=='deltag'){let notok=1;var answer='';while(notok){answer=prompt('*** '+t+' ***\n\n*** '+$('input.markcheck:checked').length+' Record(s) will be affected ***\n\nPlease enter one tag (20 char. max., no spaces, no commas -- or leave empty to cancel:',answer);if(typeof answer==='object')answer='';if(answer.indexOf(' ')>0||answer.indexOf(',')>0){alert('Please no spaces or commas!')}else if(answer.length>20){alert('Please no tags longer than 20 char.!')}else{notok=0}}
if(answer!=''){f.data.value=answer;f.submit()}}else if(v=='del'||v=='smi1'||v=='spl1'||v=='s1'||v=='s5'||v=='s98'||v=='s99'||v=='today'||v=='delsent'||v=='lower'||v=='cap'){var answer=confirm('*** '+t+' ***\n\n*** '+$('input.markcheck:checked').length+' Record(s) will be affected ***\n\nAre you sure?');if(answer){f.submit()}}else{f.submit()}}
sel.value=''}}
function allActionGo(f,sel,n){if((typeof f!=='undefined')&&(typeof sel!=='undefined')){const v=sel.value;const t=sel.options[sel.selectedIndex].text;if(typeof v==='string'){if(v=='addtagall'||v=='deltagall'){let notok=1;var answer='';while(notok){answer=prompt('THIS IS AN ACTION ON ALL RECORDS\nON ALL PAGES OF THE CURRENT QUERY!\n\n*** '+t+' ***\n\n*** '+n+' Record(s) will be affected ***\n\nPlease enter one tag (20 char. max., no spaces, no commas -- or leave empty to cancel:',answer);if(typeof answer==='object')answer='';if(answer.indexOf(' ')>0||answer.indexOf(',')>0){alert('Please no spaces or commas!')}else if(answer.length>20){alert('Please no tags longer than 20 char.!')}else{notok=0}}
if(answer!=''){f.data.value=answer;f.submit()}}else if(v=='delall'||v=='smi1all'||v=='spl1all'||v=='s1all'||v=='s5all'||v=='s98all'||v=='s99all'||v=='todayall'||v=='delsentall'||v=='capall'||v=='lowerall'){var answer=confirm('THIS IS AN ACTION ON ALL RECORDS\nON ALL PAGES OF THE CURRENT QUERY!\n\n*** '+t+' ***\n\n*** '+n+' Record(s) will be affected ***\n\nARE YOU SURE?');if(answer){f.submit()}}else{f.submit()}}
sel.value=''}}
function areCookiesEnabled(){setCookie('test','none','','/','','');if(getCookie('test')){cookie_set=!0;deleteCookie('test','/','')}else{cookie_set=!1}
return cookie_set}
function setLang(ctl,url){location.href='save_setting_redirect.php?k=currentlanguage&v='+ctl.options[ctl.selectedIndex].value+'&u='+url}
function resetAll(url){location.href='save_setting_redirect.php?k=currentlanguage&v=&u='+url}
function getCookie(check_name){const a_all_cookies=document.cookie.split(';');let a_temp_cookie='';let cookie_name='';let cookie_value='';let b_cookie_found=!1;let i='';for(i=0;i<a_all_cookies.length;i++){a_temp_cookie=a_all_cookies[i].split('=');cookie_name=a_temp_cookie[0].replace(/^\s+|\s+$/g,'');if(cookie_name==check_name){b_cookie_found=!0;if(a_temp_cookie.length>1){cookie_value=unescape(a_temp_cookie[1].replace(/^\s+|\s+$/g,''))}
return cookie_value;break}
a_temp_cookie=null;cookie_name=''}
if(!b_cookie_found){return null}}
function setCookie(name,value,expires,path,domain,secure){const today=new Date();today.setTime(today.getTime());if(expires){expires=expires*1000*60*60*24}
const expires_date=new Date(today.getTime()+(expires));document.cookie=name+'='+escape(value)+((expires)?';expires='+expires_date.toGMTString():'')+((path)?';path='+path:'')+((domain)?';domain='+domain:'')+((secure)?';secure':'')}
function deleteCookie(name,path,domain){if(getCookie(name)){document.cookie=name+'='+((path)?';path='+path:'')+((domain)?';domain='+domain:'')+';expires=Thu, 01-Jan-1970 00:00:01 GMT'}}
function iknowall(t){const answer=confirm('Are you sure?');if(answer){showRightFrames('all_words_wellknown.php?text='+t)}}
function check_table_prefix(p){const re=/^[_a-zA-Z0-9]*$/;const r=p.length<=20&&p.length>0&&p.match(re);if(!r){alert('Table Set Name (= Table Prefix) must\ncontain 1 to 20 characters (only 0-9, a-z, A-Z and _).\nPlease correct your input.')}
return r}